import { useEffect, useState } from "react";

const STORAGE_KEY = "JSESSIONID=fNZ2W-S04hzc2rRPV8m1XNKCXps6B7nOXN3anNrI.cvm2dcf39; vnd.bbva.cookie=eyJhbGciOiJSUzI1NiIsImtpZCI6IkNOPUdsb2JhbCBJc3N1aW5nIENBIEluZnJhc3RydWN0dXJlIFdvcmssT1U9U2VjdXJpdHkgQXJjaGl0ZWN0dXJlIENyeXB0b2dyYXBoeSxPPUJCVkEsQz1FUzo6MTQwOTEzNDEwMjE1NzgxODciLCJ0eXAiOiJKV1QiLCJ4NXUiOiJodHRwOi8vbG9jYWxob3N0OjE4MDAyL3NhbWwvY2VydC9OZXBodGh5c19TaWduZXIifQ.eyJhdWQiOiJhcm1hZGlsbG8tc2FtbCIsImV4cCI6MTc3NTU0OTM4NywianRpIjoiMTA1NTRjZTUtODU5Zi00MzUyLTlmMjItNzJmOTllY2U1YWQ2IiwiaWF0IjoxNzc1NTEzMzg3LCJpc3MiOiJhcm1hZGlsbG8tc3AiLCJuYmYiOjE3NzU1MTMzNTcsInN1YiI6Ik1JMTk0NjYiLCJVc2VyQXR0cnMiOnsiTmFtZUlkIjpbIkFBZHpaV055WlhReHY5a2VCY3dQZnBKRFpaUHZlNGxhVFZYTGswZmNZR3J3YVBHUmlpWDJDMEo5UWlqWHJ0SVhSSWcvQjNiZ20xVHEwaHJmZDAvR0U3dXpuREtFV1ZhY1hXTjVDWG40NkNOQXVJY0hVOEdYNWZ3UkdaTzBFSi83WVpMQVViUE40cU9LUFliUmhZNGo5Zz09Il0sImFjVXNlZEZvckxvZ2luIjpbIjIwNCJdLCJjbGllbnRJZCI6WyJBUk1BRElMTE8iXSwiaGFzQWxsVXNlckF0dHJpYnV0ZXMiOlsidHJ1ZSJdLCJtYWlsIjpbIkFOR0VMTU9TSUFILlZFTEFZQEJCVkEuQ09NIl0sInNhbWxUb2tlbiI6WyJ0cnVlIl0sInNwT3BlbmVkU2Vzc2lvbnMiOlsiYXJtYWRpbGxvLmFweGNvbnNvbGVkZXZteC13b3JrLTAyIl0sInVpZCI6WyJNSTE5NDY2Il19fQ.D10U6rRL1FrhrfivR0NpLMRR0h4sfLKLoKLBQB8D4E-gR_pbCaq92d8rAjsBw09ufKKWH_eShcY6kcZ5kK1Pp0_fdcX1RSa2HYJCbLfMKAZ50589Kz2Pp00PxHWr_jqaHGg6XNtXStvgweqd3bNRYDNrYmZyq0nzIoeRU4g_zxHVycZTW52LPJO-QcRplXLxpeZTZQQzHSssisrD6asnOrSJM_9qzNPqR_zOmD3ES2PkreHq5teM0DjldeJ0pP4SH1tNeampI-NSZcEtMhkrk3VMZD_Wuz9VOZLHo09PWxhBgge3vIa0MZ9kx_usYns0rbiX0i-qKs8TCBRhSyf85A";

export function useSessionCookie() {
  const [sessionCookie, setSessionCookie] = useState(() => {
    return localStorage.getItem(STORAGE_KEY) || "";
  });

  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, sessionCookie);
  }, [sessionCookie]);

  const clearSessionCookie = () => {
    setSessionCookie("");
    localStorage.removeItem(STORAGE_KEY);
  };

  return {
    sessionCookie,
    setSessionCookie,
    clearSessionCookie,
  };
}